//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazilimYapimi.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcDbProjeEntities : DbContext
    {
        public MvcDbProjeEntities()
            : base("name=MvcDbProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tableConfirmMoney> tableConfirmMoney { get; set; }
        public virtual DbSet<tableConfirmProduct> tableConfirmProduct { get; set; }
        public virtual DbSet<tableProduct> tableProduct { get; set; }
        public virtual DbSet<tableUser> tableUser { get; set; }
        public virtual DbSet<tableWallet> tableWallet { get; set; }
        public virtual DbSet<tableOrder> tableOrder { get; set; }
    }
}
