//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yazilimYapimi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableOrder
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual tableUser tableUser { get; set; }
    }
}
